#!/bin/sh
#
# init script for a Java application
#

# Check the application status
#
# This function checks if the application is running



######## edit ########

Appname=planty
jar= /opt/piApi/target/planty-0.1.0.jar
logfile=/opt/piApi/log/planty.log
######################


check_status() {

  # Running ps with some arguments to check if the PID exists
   s=`pgrep -f "${jar}"`

  # If somethig was returned by the ps command, this function returns the PID
  if [ $s ] ; then
    return $s
  fi

  # In any another case, return 0
  return 0

}

# Starts the application
start() {

  # At first checks if the application is already started calling the check_status
  # function
  check_status

  # $? is a special variable that hold the "exit status of the most recently executed
  # foreground pipeline"
  pid=$?

  if [ $pid -ne 0 ] ; then
    echo "The $Appname is already started"
    exit 1
  fi

  # If the application isn't running, starts it
  echo -n "Starting $Appname: "

  # Redirects default and error output to a log file
  java -jar $jar >> $logfile 2>&1 &
  echo "OK"
}

# Stops the application
stop() {

  # Like as the start function, checks the application status
  check_status

  pid=$?

  if [ $pid -eq 0 ] ; then
    echo "$Appname is already stopped"
    exit 1
  fi

  # Kills the application process
  echo -n "Stopping $Appname: "
  kill -9 $pid &
  echo "OK"
}

# Show the application status
status() {

  # The check_status function, again...
  check_status

  # If the PID was returned means the application is running
  if [ $? -ne 0 ] ; then
    echo "$Appname is started"
  else
    echo "$Appname is stopped"
  fi

}

# Main logic, a simple case to call functions
case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    status
    ;;
  restart|reload)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|reload|status}"
    exit 1
esac

exit 0